name: 'RAWADVENTUREProject'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  RAWADVENTUREProject:

    staging:
      +database: FEA24_11
      +schema: stg_certification
      +materialized: view
      erp: {}

    intermadiate:
      +database: FEA24_11
      +schema: int_certification
      +materialized: view

    marts:
      +database: FEA24_11
      +schema: marts_certification
      +materialized: table


